import sqlite3


def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None

    conn = sqlite3.connect(db_file)

    return conn


def select_all_tasks(conn, query):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    cur.execute(query)

    rows = cur.fetchall()

    for row in rows:
        print(row)


c = create_connection('birdrecordingdb.sqlite')
select_all_tasks(c, "SELECT en,count(*) FROM BirdRecordings GROUP BY en HAVING cnt='Singapore' ")

# Quality Breakdown 14128 A, 24083 B, 15281 C, 4627 D, 1199 E, 2425 'no score',

# Sampling Breakdown ('smpRate', 'amount of times in data')
# ('0', 1)
# ('11025', 21)
# ('12000', 7)
# ('16000', 239)
# ('192000', 1)
# ('22050', 686)
# ('24000', 439)
# ('256000', 1)
# ('32000', 414)
# ('384000', 3)
# ('44100', 38970)
# ('441000', 10)
# ('48000', 20795)
# ('8000', 71)
# ('88200', 24)
# ('96000', 71)

# 96.78% of our data is either 44100 or 48000

# Amounts per species. May be worth noting that some have basically no data (there are 230 species it seems)
# Seems 156 species have above 50 samples
# ("Abbott's Babbler", 165)
# ('Amur Paradise Flycatcher', 21)
# ('Arctic Warbler', 444)
# ('Ashy Drongo', 165)
# ('Ashy Minivet', 135)
# ('Ashy Tailorbird', 144)
# ('Asian Brown Flycatcher', 432)
# ('Asian Emerald Cuckoo', 8)
# ('Asian Fairy-bluebird', 181)
# ('Asian Glossy Starling', 70)
# ('Asian Koel', 322)
# ('Asian Red-eyed Bulbul', 24)
# ('Bali Myna', 27)
# ('Band-bellied Crake', 15)
# ('Banded Bay Cuckoo', 136)
# ('Banded Woodpecker', 44)
# ('Barn Swallow', 1635)
# ('Barred Eagle-Owl', 34)
# ('Baya Weaver', 58)
# ('Black Hornbill', 49)
# ('Black-and-red Broadbill', 54)
# ('Black-browed Reed Warbler', 149)
# ('Black-crested Bulbul', 147)
# ('Black-crowned Night Heron', 895)
# ('Black-headed Bulbul', 108)
# ('Black-naped Oriole', 288)
# ('Black-nest Swiftlet', 2)
# ('Black-throated Laughingthrush', 76)
# ('Black-winged Flycatcher-shrike', 26)
# ('Black-winged Kite', 263)
# ('Blue Whistling Thrush', 137)
# ('Blue-crowned Hanging Parrot', 27)
# ('Blue-eared Kingfisher', 27)
# ('Blue-rumped Parrot', 39)
# ('Blue-tailed Bee-eater', 73)
# ('Blue-throated Bee-eater', 35)
# ('Blue-winged Leafbird', 85)
# ('Blue-winged Pitta', 81)
# ("Blyth's Paradise Flycatcher", 78)
# ('Booted Warbler', 138)
# ('Brahminy Kite', 63)
# ('Bridled Tern', 28)
# ('Brown Hawk-Owl', 162)
# ('Brown Shrike', 160)
# ('Brown-chested Jungle Flycatcher', 18)
# ('Brown-streaked Flycatcher', 11)
# ('Brown-throated Sunbird', 118)
# ('Changeable Hawk-Eagle', 102)
# ('Chestnut Munia', 23)
# ('Chestnut-bellied Malkoha', 5)
# ('Chestnut-winged Babbler', 106)
# ('Chestnut-winged Cuckoo', 52)
# ('Chinese Blue Flycatcher', 29)
# ('Chinese Hwamei', 73)
# ('Chinese Sparrowhawk', 11)
# ('Cinereous Bulbul', 38)
# ('Cinnamon-headed Green Pigeon', 12)
# ('Coconut Lorikeet', 53)
# ('Collared Kingfisher', 123)
# ('Common Emerald Dove', 89)
# ('Common Flameback', 47)
# ('Common Greenshank', 902)
# ('Common Hill Myna', 167)
# ('Common Iora', 281)
# ('Common Kingfisher', 811)
# ('Common Myna', 287)
# ('Common Redshank', 1218)
# ('Common Sandpiper', 1437)
# ('Common Tailorbird', 340)
# ('Common Waxbill', 302)
# ('Copper-throated Sunbird', 28)
# ('Coppersmith Barbet', 165)
# ('Cream-vented Bulbul', 42)
# ('Crested Goshawk', 29)
# ('Crested Honey Buzzard', 228)
# ('Crested Serpent Eagle', 225)
# ('Crimson Sunbird', 103)
# ('Crow-billed Drongo', 45)
# ('Dark-necked Tailorbird', 222)
# ('Daurian Starling', 15)
# ('Eastern Crowned Warbler', 260)
# ('Eastern Yellow Wagtail', 253)
# ('Edible-nest Swiftlet', 10)
# ('Eurasian Tree Sparrow', 2443)
# ('Eurasian Whimbrel', 922)
# ('Eyebrowed Thrush', 166)
# ('Golden-backed Weaver', 14)
# ('Golden-bellied Gerygone', 60)
# ('Great Slaty Woodpecker', 124)
# ('Great-billed Heron', 17)
# ('Greater Coucal', 223)
# ('Greater Crested Tern', 47)
# ('Greater Green Leafbird', 55)
# ('Greater Painted-snipe', 19)
# ('Greater Racket-tailed Drongo', 402)
# ('Green Broadbill', 60)
# ('Green Imperial Pigeon', 92)
# ('Green-backed Flycatcher', 55)
# ('Grey Heron', 1414)
# ('Grey Plover', 529)
# ('Grey Wagtail', 808)
# ('Grey-faced Buzzard', 41)
# ('Grey-headed Fish Eagle', 26)
# ('Grey-rumped Treeswift', 38)
# ('Half-collared Kingfisher', 14)
# ('Hooded Pitta', 142)
# ('House Crow', 169)
# ('House Sparrow', 2340)
# ('House Swift', 57)
# ('Identity unknown', 16089)
# ('Indian Cuckoo', 175)
# ('Indian Paradise Flycatcher', 47)
# ('Indochinese Blue Flycatcher', 65)
# ('Japanese Sparrowhawk', 21)
# ('Japanese Tit', 439)
# ('Javan Munia', 10)
# ('Javan Myna', 47)
# ("Jerdon's Baza", 14)
# ('King Quail', 9)
# ('Laced Woodpecker', 46)
# ('Lanceolated Warbler', 96)
# ('Large Woodshrike', 55)
# ('Large-billed Crow', 307)
# ('Large-tailed Nightjar', 209)
# ('Lesser Coucal', 75)
# ('Lesser Sand Plover', 53)
# ('Lesser Whistling Duck', 54)
# ('Lineated Barbet', 124)
# ('Little Bronze Cuckoo', 81)
# ('Little Egret', 473)
# ('Little Grebe', 1264)
# ('Little Spiderhunter', 181)
# ('Little Tern', 331)
# ('Long-tailed Parakeet', 57)
# ('Long-tailed Shrike', 157)
# ('Malaysian Hawk-Cuckoo', 37)
# ('Malaysian Pied Fantail', 102)
# ('Malaysian Plover', 3)
# ('Mangrove Blue Flycatcher', 43)
# ('Mangrove Pitta', 46)
# ('Mangrove Whistler', 82)
# ('Masked Lapwing', 60)
# ('Mugimaki Flycatcher', 79)
# ('Mute Swan', 497)
# ('Olive-backed Sunbird', 283)
# ('Olive-winged Bulbul', 63)
# ('Orange-bellied Flowerpecker', 125)
# ('Orange-headed Thrush', 95)
# ('Oriental Darter', 18)
# ('Oriental Dollarbird', 103)
# ('Oriental Magpie-Robin', 531)
# ('Oriental Pied Hornbill', 94)
# ('Oriental Reed Warbler', 161)
# ('Pacific Golden Plover', 170)
# ('Pacific Reef Heron', 8)
# ('Pacific Swallow', 58)
# ('Paddyfield Pipit', 91)
# ('Pale-legged Leaf Warbler', 152)
# ("Pallas's Grasshopper Warbler", 131)
# ('Pied Imperial Pigeon', 14)
# ('Pied Triller', 28)
# ('Pin-striped Tit-Babbler', 268)
# ('Pink-necked Green Pigeon', 30)
# ('Plaintive Cuckoo', 182)
# ('Plume-toed Swiftlet', 19)
# ('Purple Heron', 238)
# ('Red Avadavat', 69)
# ('Red Junglefowl', 150)
# ('Red Turtle Dove', 25)
# ('Red-billed Blue Magpie', 91)
# ('Red-breasted Parakeet', 92)
# ('Red-crowned Barbet', 50)
# ('Red-legged Crake', 45)
# ('Red-necked Stint', 41)
# ('Red-throated Pipit', 401)
# ('Red-wattled Lapwing', 174)
# ('Red-whiskered Bulbul', 211)
# ('Rose-ringed Parakeet', 435)
# ('Ruby-cheeked Sunbird', 49)
# ('Ruddy Kingfisher', 149)
# ('Ruddy Turnstone', 364)
# ('Ruddy-breasted Crake', 50)
# ('Rufous Woodpecker', 78)
# ('Rufous-collared Kingfisher', 51)
# ('Rufous-tailed Tailorbird', 141)
# ('Rusty-breasted Cuckoo', 136)
# ('Sakhalin Leaf Warbler', 174)
# ('Savanna Nightjar', 97)
# ('Scaly-breasted Munia', 120)
# ('Scarlet-backed Flowerpecker', 89)
# ('Short-tailed Babbler', 61)
# ('Siberian Blue Robin', 137)
# ('Siberian Thrush', 44)
# ('Slaty-breasted Rail', 29)
# ('Sooty-headed Bulbul', 97)
# ('Spotted Dove', 204)
# ('Spotted Wood Owl', 39)
# ('Square-tailed Drongo-Cuckoo', 140)
# ('Stork-billed Kingfisher', 164)
# ('Straw-headed Bulbul', 88)
# ('Streaked Bulbul', 48)
# ('Striated Heron', 169)
# ('Sunda Pygmy Woodpecker', 27)
# ('Sunda Scops Owl', 66)
# ("Swinhoe's White-eye", 132)
# ('Taiga Flycatcher', 186)
# ('Tanimbar Corella', 12)
# ('Thick-billed Green Pigeon', 32)
# ('Tiger Shrike', 22)
# ("Van Hasselt's Sunbird", 54)
# ('Violet Cuckoo', 58)
# ('Western Barn Owl', 960)
# ('White Wagtail', 1472)
# ('White-bellied Sea Eagle', 42)
# ('White-breasted Waterhen', 197)
# ('White-browed Crake', 35)
# ('White-crested Laughingthrush', 152)
# ('White-headed Munia', 12)
# ('White-rumped Shama', 304)
# ('White-throated Kingfisher', 238)
# ('Wood Sandpiper', 735)
# ('Yellow Bittern', 29)
# ('Yellow-bellied Prinia', 229)
# ('Yellow-browed Warbler', 816)
# ('Yellow-crested Cockatoo', 26)
# ('Yellow-fronted Canary', 108)
# ('Yellow-rumped Flycatcher', 112)
# ('Yellow-vented Bulbul', 109)
# ('Zebra Dove', 135)
# ('Zitting Cisticola', 854)


# (Minutes, How many times in our date) --
# This data has slight inaccuracies
# Still working on a way to extract real time
# information with seconds from a string
# it is very clear that recordings rarely go above 3 minutes.

# (0, 52076)
# (1, 6532)
# (2, 1640)
# (3, 578)
# (4, 374)
# (5, 151)
# (6, 71)
# (7, 49)
# (8, 85)
# (9, 27)
# (10, 21)
# (11, 20)
# (12, 13)
# (13, 12)
# (14, 34)
# (15, 6)
# (16, 5)
# (17, 6)
# (18, 1)
# (19, 5)
# (20, 6)
# (21, 1)
# (22, 3)
# (23, 2)
# (24, 8)
# (25, 2)
# (26, 3)
# (27, 1)
# (28, 2)
# (29, 1)
# (30, 2)
# (32, 2)
# (33, 2)
# (35, 3)
# (36, 2)
# (39, 1)
# (43, 1)
# (44, 2)
# (46, 1)
# (49, 2)


# Although all these birds are present in singapore
# only 2000 of the recordings were actually in singapore
# The following data is only captured based on birds that were recorded in Singapore,
# this is now only 53 species (and I assume the ones we are most likely
# to encounter when we travel there)

# ("Abbott's Babbler", 165)
# ('Amur Paradise Flycatcher', 21)
# ('Arctic Warbler', 444)
# ('Ashy Tailorbird', 144)
# ('Asian Glossy Starling', 70)
# ('Asian Red-eyed Bulbul', 24)
# ('Band-bellied Crake', 15)
# ('Banded Bay Cuckoo', 136)
# ('Barred Eagle-Owl', 34)
# ('Black-naped Oriole', 288)
# ('Blue-crowned Hanging Parrot', 27)
# ('Blue-rumped Parrot', 39)
# ('Brown Shrike', 160)
# ('Brown-throated Sunbird', 118)
# ('Changeable Hawk-Eagle', 102)
# ('Chinese Hwamei', 73)
# ('Cinnamon-headed Green Pigeon', 12)
# ('Coconut Lorikeet', 53)
# ('Collared Kingfisher', 123)
# ('Common Hill Myna', 167)
# ('Cream-vented Bulbul', 42)
# ('Crested Honey Buzzard', 228)
# ('Crow-billed Drongo', 45)
# ('Eastern Crowned Warbler', 260)
# ('Edible-nest Swiftlet', 10)
# ('Golden-backed Weaver', 14)
# ('Greater Painted-snipe', 19)
# ('Grey-headed Fish Eagle', 26)
# ('Grey-rumped Treeswift', 38)
# ("Jerdon's Baza", 14)
# ('Laced Woodpecker', 46)
# ('Lanceolated Warbler', 96)
# ('Large-tailed Nightjar', 209)
# ('Lineated Barbet', 124)
# ('Masked Lapwing', 60)
# ('Olive-winged Bulbul', 63)
# ('Orange-bellied Flowerpecker', 125)
# ('Oriental Pied Hornbill', 94)
# ('Pin-striped Tit-Babbler', 268)
# ('Pink-necked Green Pigeon', 30)
# ('Plaintive Cuckoo', 182)
# ('Red-crowned Barbet', 50)
# ('Scarlet-backed Flowerpecker', 89)
# ('Short-tailed Babbler', 61)
# ('Slaty-breasted Rail', 29)
# ('Spotted Wood Owl', 39)
# ('Tanimbar Corella', 12)
# ('White-bellied Sea Eagle', 42)
# ('White-headed Munia', 12)
# ('Yellow Bittern', 29)
# ('Yellow-bellied Prinia', 229)
# ('Yellow-rumped Flycatcher', 112)
# ('Yellow-vented Bulbul', 109)
